export type GameLanguage = 'en' | 'pt';

const defaultLanguage: GameLanguage = 'pt';
const languageStorageKey = 'farming-simulator-cabacos-language';

const translations = {
    en: {
        cropMarketTitle: 'Crop Market',
        sell: 'Sell',
        sold: 'Sold',
        noCropToSell: 'You do not have this crop',
        sellCrops: 'E - Sell crops',
        gameTitle: 'Cabacos Farm',
        startGame: 'Start Game',
        saveGame: 'Save Game',
        loadGame: 'Load Game',
        saveComplete: 'Game saved',
        noSaves: 'No saves found',
        selectSlot: 'Select Slot',
        slot: 'Slot',
        emptySlot: 'Empty',
        settings: 'Settings',
        settingsTitle: 'Settings',
        pauseTitle: 'Game Paused',
        resume: 'Resume',
        language: 'Language',
        english: 'English',
        portuguese: 'Portuguese',
        back: 'Back',
        gameOver: 'Game Over',
        inventoryTitle: 'Inventory',
        money: 'Money',
        energy: 'Energy',
        day: 'Day',
        seedShopTitle: 'Seed Shop',
        toolShopTitle: 'Tool Shop',
        farmPurchaseTitle: 'Farm Land',
        buy: 'Buy',
        owned: 'Owned',
        notEnoughMoney: 'Not enough money',
        inventoryFull: 'Inventory full',
        purchased: 'Purchased',
        landPurchased: 'Purchased',
        alreadyOwned: 'Already owned',
        itemAlreadyOwned: 'You already own this item',
        enterHouse: 'E - Enter house',
        enterMarket: 'E - Enter market',
        enterSeedShop: 'E - Enter shop',
        enterToolShop: 'E - Enter tool shop',
        enterTownHall: 'E - Enter town hall',
        exitBuilding: 'E - Exit',
        sleep: 'E - Sleep',
        buySeeds: 'E - Buy seeds',
        buyTools: 'E - Buy tools',
        fillWateringCan: 'E - Fill watering can',
        water: 'Water',
        buyFarms: 'E - Buy farm land',
        marketSellTab: 'Crops',
        marketQuestTab: 'Quests',
        activeQuests: 'Active Quests',
        questActive: 'Active Quest',
        questReady: 'Ready to claim',
        questProgress: 'Progress',
        reward: 'Reward',
        questActivate: 'Activate',
        questActivated: 'Quest activated',
        questAlreadyActive: 'Finish the active quest first',
        questClaim: 'Claim',
        questInProgress: 'In progress',
        questCompleted: 'Completed',
        questNotReady: 'Quest is not complete yet',
        questRewardClaimed: 'Quest completed',
        questPlantPumpkinsTitle: 'Plant Pumpkins',
        questPlantPumpkinsDescription: 'Plant 3 pumpkins on your farm.',
        questSellCarrotsTitle: 'Sell Carrots',
        questSellCarrotsDescription: 'Sell 3 carrots at the Crop Market.',
        questWaterPlantsTitle: 'Water Plants',
        questWaterPlantsDescription: 'Water any plants 10 times.',
        farm2Name: 'Farm 2',
        farm3Name: 'Farm 3',
        itemAxe: 'Axe',
        itemHoe: 'Hoe',
        itemRod: 'Fishing Rod',
        itemSickle: 'Sickle',
        itemShovel: 'Shovel',
        itemSword: 'Sword',
        itemWateringCan: 'Watering Can',
        seedBeetroot: 'Beetroot Seeds',
        seedCabbage: 'Cabbage Seeds',
        seedCarrot: 'Carrot Seeds',
        seedCauliflower: 'Cauliflower Seeds',
        seedKale: 'Kale Seeds',
        seedParsnip: 'Parsnip Seeds',
        seedPotato: 'Potato Seeds',
        seedPumpkin: 'Pumpkin Seeds',
        seedRadish: 'Radish Seeds',
        seedSunflower: 'Sunflower Seeds',
        seedWheat: 'Wheat Seeds',
        cropBeetroot: 'Beetroot',
        cropCabbage: 'Cabbage',
        cropCarrot: 'Carrot',
        cropCauliflower: 'Cauliflower',
        cropKale: 'Kale',
        cropParsnip: 'Parsnip',
        cropPotato: 'Potato',
        cropPumpkin: 'Pumpkin',
        cropRadish: 'Radish',
        cropSunflower: 'Sunflower',
        cropWheat: 'Wheat'
    },
    pt: {
        cropMarketTitle: 'Mercado de Colheitas',
        sell: 'Vender',
        sold: 'Vendeste',
        noCropToSell: 'Nao tens esta colheita',
        sellCrops: 'E - Vender colheitas',
        gameTitle: 'Quinta Cabacos',
        startGame: 'Começar Jogo',
        saveGame: 'Guardar Jogo',
        loadGame: 'Carregar Jogo',
        saveComplete: 'Jogo guardado',
        noSaves: 'Nao ha saves',
        selectSlot: 'Escolher Save',
        slot: 'Slot',
        emptySlot: 'Vazio',
        settings: 'Definições',
        settingsTitle: 'Definições',
        pauseTitle: 'Jogo em Pausa',
        resume: 'Continuar',
        language: 'Idioma',
        english: 'Inglês',
        portuguese: 'Português',
        back: 'Voltar',
        gameOver: 'Fim do Jogo',
        inventoryTitle: 'Inventário',
        money: 'Dinheiro',
        energy: 'Energia',
        day: 'Dia',
        seedShopTitle: 'Loja de Sementes',
        toolShopTitle: 'Loja de Ferramentas',
        farmPurchaseTitle: 'Terrenos da Quinta',
        buy: 'Comprar',
        owned: 'Comprado',
        notEnoughMoney: 'Dinheiro insuficiente',
        inventoryFull: 'Inventário cheio',
        purchased: 'Compraste',
        landPurchased: 'Compraste',
        alreadyOwned: 'Terreno ja comprado',
        itemAlreadyOwned: 'Ja tens este item',
        enterHouse: 'E - Entrar em casa',
        enterMarket: 'E - Entrar no mercado',
        enterSeedShop: 'E - Entrar na loja',
        enterToolShop: 'E - Entrar na loja de ferramentas',
        enterTownHall: 'E - Entrar na câmara',
        exitBuilding: 'E - Sair',
        sleep: 'E - Dormir',
        buySeeds: 'E - Comprar sementes',
        buyTools: 'E - Comprar ferramentas',
        fillWateringCan: 'E - Encher regador',
        water: 'Agua',
        buyFarms: 'E - Comprar terrenos',
        marketSellTab: 'Colheitas',
        marketQuestTab: 'Quests',
        activeQuests: 'Quests Ativas',
        questActive: 'Quest Ativa',
        questReady: 'Pronta para concluir',
        questProgress: 'Progresso',
        reward: 'Recompensa',
        questActivate: 'Ativar',
        questActivated: 'Quest ativada',
        questAlreadyActive: 'Termina primeiro a quest ativa',
        questClaim: 'Concluir',
        questInProgress: 'Em progresso',
        questCompleted: 'Concluida',
        questNotReady: 'A quest ainda nao esta completa',
        questRewardClaimed: 'Quest concluida',
        questPlantPumpkinsTitle: 'Plantar Aboboras',
        questPlantPumpkinsDescription: 'Planta 3 aboboras na tua quinta.',
        questSellCarrotsTitle: 'Vender Cenouras',
        questSellCarrotsDescription: 'Vende 3 cenouras no Mercado de Colheitas.',
        questWaterPlantsTitle: 'Regar Plantas',
        questWaterPlantsDescription: 'Rega qualquer tipo de planta 10 vezes.',
        farm2Name: 'Farm 2',
        farm3Name: 'Farm 3',
        itemAxe: 'Machado',
        itemHoe: 'Enxada',
        itemRod: 'Cana de Pesca',
        itemSickle: 'Foice',
        itemShovel: 'Pá',
        itemSword: 'Espada',
        itemWateringCan: 'Regador',
        seedBeetroot: 'Sementes de Beterraba',
        seedCabbage: 'Sementes de Couve',
        seedCarrot: 'Sementes de Cenoura',
        seedCauliflower: 'Sementes de Couve-flor',
        seedKale: 'Sementes de Couve-galega',
        seedParsnip: 'Sementes de Pastinaca',
        seedPotato: 'Sementes de Batata',
        seedPumpkin: 'Sementes de Abóbora',
        seedRadish: 'Sementes de Rabanete',
        seedSunflower: 'Sementes de Girassol',
        seedWheat: 'Sementes de Trigo',
        cropBeetroot: 'Beterraba',
        cropCabbage: 'Couve',
        cropCarrot: 'Cenoura',
        cropCauliflower: 'Couve-flor',
        cropKale: 'Couve-galega',
        cropParsnip: 'Pastinaca',
        cropPotato: 'Batata',
        cropPumpkin: 'Abóbora',
        cropRadish: 'Rabanete',
        cropSunflower: 'Girassol',
        cropWheat: 'Trigo'
    }
};

export type TranslationKey = keyof typeof translations.en;

export function getCurrentLanguage(): GameLanguage {
    const savedLanguage = localStorage.getItem(languageStorageKey);

    if (isGameLanguage(savedLanguage)) {
        return savedLanguage;
    }

    return defaultLanguage;
}

export function setCurrentLanguage(language: GameLanguage): void {
    localStorage.setItem(languageStorageKey, language);
}

export function translate(key: TranslationKey): string {
    return translations[getCurrentLanguage()][key];
}

export function getAvailableLanguages(): GameLanguage[] {
    return ['pt', 'en'];
}

export function getLanguageLabel(language: GameLanguage): string {
    const labelKey: TranslationKey = language === 'pt' ? 'portuguese' : 'english';

    return translate(labelKey);
}

function isGameLanguage(value: string | null): value is GameLanguage {
    return value === 'en' || value === 'pt';
}
